columnSuffix: null
handle: customSpacing
instructions: null
name: 'Custom Spacing'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
