columnSuffix: null
handle: defaultOgDescription
instructions: 'Maximum 200 characters. Aim for about 25-35 words.'
name: 'Default Open Graph Description'
searchable: false
settings:
  byteLimit: null
  charLimit: 200
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
