import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { ResponsiveStyleValue, StyleValue } from "../src/lib/styles";
import {
  expandColorTokensForTheme,
  renderColorAliases,
  renderColorMap,
  renderCssVarAliases,
  renderLayoutMapInput,
  renderMixedResponsiveCssVars,
  renderResponsiveCssVars,
  renderScssMap,
  renderThemedColorCssVars,
  renderTokenAliases,
  renderTokenCssVars,
  renderUtilities,
} from "../src/lib/styles";
import { styleVars } from "../src/styles/vars";
import { scriptLog } from "./logger";

const logger = scriptLog("styles");
const scriptDir = dirname(fileURLToPath(import.meta.url));
const appRoot = resolve(scriptDir, "..");
const mapsOutputPath = resolve(appRoot, "src/styles/maps.generated.scss");
const rootOutputPath = resolve(appRoot, "src/styles/root.generated.scss");
const varsOutputPath = resolve(appRoot, "src/styles/vars.generated.scss");
const tsVarsOutputPath = resolve(appRoot, "src/styles/vars.generated.ts");
const utilitiesOutputPath = resolve(
  appRoot,
  "src/styles/utilities.generated.scss",
);

const generatedHeader = [
  "// Generated by app/scripts/generate-vars.ts.",
  "// Do not edit manually.",
  "",
].join("\n");

const renderBreakpointAliases = (breakpoints: Record<string, { value: string }>) =>
  Object.entries(breakpoints)
    .map(([name, value]) => `$breakpoint-${name}: ${value.value};`)
    .join("\n");

const isStyleValue = (value: unknown): value is StyleValue =>
  typeof value === "object" && value !== null && "value" in value;

const isResponsiveStyleValue = (
  value: unknown,
): value is ResponsiveStyleValue =>
  typeof value === "object" &&
  value !== null &&
  !isStyleValue(value) &&
  Object.values(value).every(isStyleValue);

const isResponsiveTokenSource = (
  tokens: Record<string, unknown>,
): tokens is Record<string, ResponsiveStyleValue> =>
  Object.values(tokens).every(isResponsiveStyleValue);

const toCamelCase = (value: string) =>
  value.replace(/-([a-z0-9])/g, (_, char: string) => char.toUpperCase());

const defaultThemeName = () => {
  const explicitDefault = Object.entries(styleVars.themes).find(
    ([, theme]) => "default" in theme && theme.default === true,
  );

  return explicitDefault?.[0] ?? Object.keys(styleVars.themes)[0];
};

const runtimeValue = (value: StyleValue) => value.value;

const runtimeDurationValue = (value: StyleValue) => {
  if (value.value.endsWith("s")) {
    return Number(value.value.slice(0, -1));
  }

  return value.value;
};

const renderRuntimeTokens = <TValue>(
  tokens: Record<string, TValue>,
  transform: (value: TValue) => unknown,
) =>
  Object.fromEntries(
    Object.entries(tokens).map(([name, value]) => [
      toCamelCase(name),
      transform(value),
    ]),
  );

const renderRuntimeResponsiveTokens = (
  tokens: Record<string, ResponsiveStyleValue>,
) =>
  renderRuntimeTokens(tokens, (value) =>
    renderRuntimeTokens(value, runtimeValue),
  );

const renderRuntimeMixedTokens = (
  tokens: Record<string, ResponsiveStyleValue | StyleValue>,
) =>
  renderRuntimeTokens(tokens, (value) =>
    isStyleValue(value)
      ? runtimeValue(value)
      : renderRuntimeTokens(value, runtimeValue),
  );

const renderRuntimeColors = () => {
  const baseTheme = defaultThemeName();
  const themes = Object.fromEntries(
    Object.keys(styleVars.themes).map((themeName) => [
      themeName,
      renderRuntimeTokens(
        expandColorTokensForTheme(styleVars.colors, themeName),
        (value) => value,
      ),
    ]),
  );

  return {
    ...themes[baseTheme],
    themes,
  };
};

const isValidTsPropertyName = (value: string) =>
  /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value);

const renderTsPropertyName = (name: string) =>
  isValidTsPropertyName(name) ? name : JSON.stringify(name);

const renderTsValue = (value: unknown, depth = 0): string => {
  const indent = "\t".repeat(depth);
  const childIndent = "\t".repeat(depth + 1);

  if (Array.isArray(value)) {
    if (!value.length) {
      return "[]";
    }

    return [
      "[",
      ...value.map((item) => `${childIndent}${renderTsValue(item, depth + 1)},`),
      `${indent}]`,
    ].join("\n");
  }

  if (typeof value === "object" && value !== null) {
    const entries = Object.entries(value);

    if (!entries.length) {
      return "{}";
    }

    return [
      "{",
      ...entries.map(
        ([name, item]) =>
          `${childIndent}${renderTsPropertyName(name)}: ${renderTsValue(item, depth + 1)},`,
      ),
      `${indent}}`,
    ].join("\n");
  }

  return JSON.stringify(value);
};

const utilityTokenEntries = Array.from(
  new Map<string, Record<string, ResponsiveStyleValue>>(
    styleVars.utilities.flatMap((utility) =>
      isResponsiveTokenSource(utility.tokens)
        ? [[utility.namespace, utility.tokens] as const]
        : [],
    ),
  ).entries(),
);

const renderUtilityTokenMaps = () =>
  utilityTokenEntries
    .map(([namespace, tokens]) => renderScssMap(namespace, tokens))
    .join("\n\n");

const renderUtilityTokenRootVars = () =>
  utilityTokenEntries
    .map(([namespace, tokens]) =>
      renderResponsiveCssVars(
        namespace,
        tokens,
        styleVars.breakpoints,
        styleVars.responsiveBase,
      ),
    )
    .join("\n\n");

const renderUtilityTokenAliases = () =>
  utilityTokenEntries
    .map(([namespace, tokens]) => renderCssVarAliases(namespace, tokens))
    .join("\n\n");

const mapsContent = [
  generatedHeader,
  renderScssMap("breakpoints", styleVars.breakpoints),
  "",
  renderUtilityTokenMaps(),
  "",
  renderScssMap(
    "color-tokens",
    renderColorMap(styleVars.colors, styleVars.themes) as Parameters<
      typeof renderScssMap
    >[1],
  ),
  "",
  renderScssMap("durations", styleVars.durations),
  "",
  renderScssMap("easings", styleVars.easings),
  "",
  renderScssMap("page", renderLayoutMapInput(styleVars.page)),
  "",
  renderScssMap("container", renderLayoutMapInput(styleVars.container)),
  "",
].join("\n");

const rootContent = [
  generatedHeader,
  renderUtilityTokenRootVars(),
  "",
  renderThemedColorCssVars("color", styleVars.colors, styleVars.themes),
  "",
  renderTokenCssVars("duration", styleVars.durations),
  "",
  renderTokenCssVars("ease", styleVars.easings),
  "",
  renderMixedResponsiveCssVars(
    "page",
    styleVars.page,
    styleVars.breakpoints,
    styleVars.responsiveBase,
  ),
  "",
  renderMixedResponsiveCssVars(
    "container",
    styleVars.container,
    styleVars.breakpoints,
    styleVars.responsiveBase,
  ),
  "",
].join("\n");

const varsContent = [
  generatedHeader,
  renderBreakpointAliases(styleVars.breakpoints),
  "",
  renderUtilityTokenAliases(),
  "",
  renderColorAliases("color", styleVars.colors),
  "",
  renderTokenAliases("duration", styleVars.durations),
  "",
  renderTokenAliases("ease", styleVars.easings),
  "",
  renderCssVarAliases("page", styleVars.page),
  "",
  renderCssVarAliases("container", styleVars.container),
  "",
].join("\n");

const utilitiesContent = [
  generatedHeader,
  renderUtilities(styleVars.utilities),
  "",
].join("\n");

const tsVarsContent = [
  generatedHeader,
  `export const vars = ${renderTsValue({
    breakpoints: renderRuntimeTokens(styleVars.breakpoints, runtimeValue),
    responsiveBase: styleVars.responsiveBase,
    themes: Object.keys(styleVars.themes),
    space: renderRuntimeResponsiveTokens(styleVars.space),
    colors: renderRuntimeColors(),
    durations: renderRuntimeTokens(styleVars.durations, runtimeDurationValue),
    easings: renderRuntimeTokens(styleVars.easings, runtimeValue),
    page: renderRuntimeMixedTokens(styleVars.page),
    container: renderRuntimeMixedTokens(styleVars.container),
  })} as const;\n`,
  "export type StyleVars = typeof vars;\n",
].join("");

const generateStep = logger.step("generate style artifacts");

await mkdir(dirname(mapsOutputPath), { recursive: true });
await mkdir(dirname(rootOutputPath), { recursive: true });
await mkdir(dirname(varsOutputPath), { recursive: true });
await mkdir(dirname(tsVarsOutputPath), { recursive: true });
await mkdir(dirname(utilitiesOutputPath), { recursive: true });
await writeFile(mapsOutputPath, mapsContent);
await writeFile(rootOutputPath, rootContent);
await writeFile(varsOutputPath, varsContent);
await writeFile(tsVarsOutputPath, tsVarsContent);
await writeFile(utilitiesOutputPath, utilitiesContent);

generateStep.done("generated style artifacts", {
  files: [
    mapsOutputPath,
    rootOutputPath,
    varsOutputPath,
    tsVarsOutputPath,
    utilitiesOutputPath,
  ],
});
